### ISSUE TITLE
Could you please elaborate more on readme section on "HOw to download perticular subject book download"

### ISSUE THREAD

**Issue by pspatel011** [alexgand/springer_free_books#1]
And also can i download books from perticular subject like machich learning or data science in one script?

**Comment by alexgand** [comment]
Hi. The excel file (https://resource-cms.springernature.com/springer-cms/rest/v1/content/17858272/data/v3) contains a "Subject Classification" column, but its content is very disperse. If you want to download a specific book, just use the link for that book which is on column "OpenURL".

**Comment by alexgand** [comment]
Hi, in fact there is a column called "English Package Name" in data that seems to be the subject of the book.
I updated the code and now the downloaded books are now organized in folders by subject!
