### ISSUE TITLE
Please share the archive

### ISSUE THREAD

**Issue by xvladqt** [alexgand/springer_free_books#115]
Hello. Can anyone share a full archive of books on cloud or via torrent, with partial download capability? Currently, i cannot use this script for do this.

**Comment by SuperSandro2000** [comment]
There is a dumb on: https://t.me/SpringerEBooks 
I don't know if it is legit.

**Comment by xvladqt** [comment]
Thank. I did not find any mention of which license was used for publication. It may be illegal.
