### ISSUE TITLE
Workaround just FYI

### ISSUE THREAD

**Issue by 573** [alexgand/springer_free_books#12]
To circumvent redownloading aborted downloads you can just add:
```
import os
import curlify as cy
```
and replace the two `open(new_folder+final, 'wb').write(myfile.content)` statements with:
```
os.popen("{}{}\"{}\"{}".format(cy.to_curl(myfile.request), " -o ", new_folder+final, " -C -").replace("'", "\""))
```
Assumes a working `curl` binary nonetheless on your system.

**Comment by alexgand** [comment]
Ok, thanks!
