### ISSUE TITLE
Can't get the requirements to work

### ISSUE THREAD

**Issue by MarcusWolschon** [alexgand/springer_free_books#15]
I'm not normally using python at all.
Aparently pip can't find any of the requirements.
(The machine is online via IPv6. I tested by also giving the machine some legacy IPv4. No improvement.)

How do I tell it where to look for these requirements?
(The requirements listed also don't exist as Debian packages to install them manually, without pip.)

Example:
```
/tmp# python3 -m venv .venv
/tmp# . .venv/bin/activate
(.venv) 
/tmp# pip install -r requirements.txt
Collecting certifi==2020.4.5.1 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement certifi==2020.4.5.1 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for certifi==2020.4.5.1 (from -r requirements.txt (line 1))
```

**Comment by emmaKts** [comment]
Hi, have you maybe tried without specifying the version?
```sh
(venv) pip install certifi
```

**Comment by MarcusWolschon** [comment]
Yes, I have. Same result.

**Comment by alexgand** [comment]
Try again, several improvements were made on the code.
