### ISSUE TITLE
GUI?  Available if you want one.

### ISSUE THREAD

**Issue by PySimpleGUI** [alexgand/springer_free_books#31]
Awesome program!

I've added a GUI onto your code and replaced tqdm with a graphical progress meter that includes stats and a mechanism to cancel the operation.  It only changed 7 lines in the code.

A GUI provides a number of benefits at little / no cost

* Setting the location to save without modifying the source code
* A progress meter with stats
    * Shows overall progress
    * Shows time remaining
    * Ability to "cancel" the download in a safer manner than a Control C or killing the process
* Popup error messages so that you can run the entire program without a console
* Can distribute as an EXE file / py file that runs without a console

I forked your project and made the changes to my version.  I didn't want to do a pull request as you may be fine with running on the command line, or maybe want to enable both modes by adding a "-gui" parameter when the program is started.  It's your project so don't want to be presumptuous about any changes I made.  If you're not interested, no problem, I'll just rename my version so there's no confusion.

--------------------

### GUI Screenshots

Startup

You can copy and paste the folder location into the window or use the Browse button.

![image](https://user-images.githubusercontent.com/46163555/79893832-98e90400-83d2-11ea-8b43-baef5a69dee8.png)

After the download starts, the progress meter is shown that shows the current book as well as stats about time spent so far and time remaining (based on how long it's taken so far)

![image](https://user-images.githubusercontent.com/46163555/79893157-a2be3780-83d1-11ea-86fc-73c7a028cf61.png)

If you click "cancel" or close the progress meter window, then you'll be shown another popu-up window so that you understand why the download has stopped and the program exited

![image](https://user-images.githubusercontent.com/46163555/79893457-1e1fe900-83d2-11ea-9f53-785abc6562ad.png)

--------------------

Possible confusing situation with "not responsive" message.

Because the GUI was added on top of code that blocks for long periods of time while downloading, Windows will sometimes display a "not responsive" message then the user tries to cancel the operation.  

The problem could be solved by threading the downloading portion so that it doesn't simply pend for long periods of time, but the added complexity isn't likely worth it.  A simple message "Your program hasn't locked up, it just looks busy during downloading" would explain the situation to users if desired.

**Comment by alexgand** [comment]
Hi, awesome work, thanks!
I'll leave the code for the original project just on CLI, though.
It's for the sake of simplicity. For some people this was their introduction to python, so I'll keep it as simple as possible.

**Comment by SgtPooki** [comment]
@PySimpleGUI you should fork the repo and add your GUI and link us to it.

**Comment by PySimpleGUI** [comment]
Yea, I did that for a bit, but the focus is on the GUI and wanted to name like the other PySimpleGUI projects.  I'll add some info in the Readme and link back in a more serious manner however.

**Comment by PySimpleGUI** [comment]
Here's my repo:
https://github.com/PySimpleGUI/SpringerFreeBooks_GUI

I see now that I look that I link back to this repo in the first sentence of the readme.
