### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by victormm2000** [alexgand/springer_free_books#34]
When I click on run in Python with the main.py, I can't start the download

**Comment by marethyu** [comment]
open the terminal and type `pip3 install requests`

**Comment by alexgand** [comment]
Try ```pip install -r requirements.txt```.

**Comment by victormm2000** [comment]
![image](https://user-images.githubusercontent.com/64150939/80079766-00c55900-8551-11ea-9a8e-b77255f528b0.png)

![image](https://user-images.githubusercontent.com/64150939/80079826-1175cf00-8551-11ea-927b-5673f2afdae7.png)

I don't know...

**Comment by marethyu** [comment]
use terminal (command prompt) not python shell
