### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by sundrb** [alexgand/springer_free_books#38]
![image](https://user-images.githubusercontent.com/55596936/80128596-8679f080-85b3-11ea-8942-8120d374baf3.png)

How do I overcome this error?

I have changed my download folder 
![image](https://user-images.githubusercontent.com/55596936/80128701-a90c0980-85b3-11ea-9956-9c44a2521094.png)

No other changes done.

**Comment by chaosAD** [comment]
No, it won't work. Try the following:
```
# insert here the folder you want the books to be downloaded:
folder = r'C:\sundarb\downloads'

if not os.path.exists(folder):
    os.makedirs(folder)
```
The letter `r` before the string is important. Otherwise you get the same error you showed. You can't use ```C:\Users\...``` because of access permission reason. Take note of the ```os.makedirs()``` function. The ```os.mkdir()``` only works for creating a single level of directory.

**Comment by alexgand** [comment]
Please try again, the code was modified and is now much better.
