### ISSUE TITLE
Incomplete downloaded book considered valid after restarting script

### ISSUE THREAD

**Issue by chaosAD** [alexgand/springer_free_books#41]
For some reason if a user hit Ctrl+C or Ctrl+Break, the incomplete downloaded book would be considered a valid book and would not be replaced on restarting the script.

Also on restart, if a PDF file is present (but incomplete, due to Ctrl+C or Ctrl+Break), its EPUB will be skipped.

**Comment by alexgand** [comment]
Solved in the last code update.
