### ISSUE TITLE
Downloaded files are not visible.

### ISSUE THREAD

**Issue by ankitemb** [alexgand/springer_free_books#51]
Hello,

I am not able to see the download content in my local directory. Is it download somewhere else?
I clone this repo and created the downloads folder in springer_free_books folder.
I used following command to download the content:
1) sudo docker build . -t springer-image
2) sudo docker run --rm -v downloads springer-image

After completion of 100% I am not able to see any of the book in the local folder which pointed in second command. Please help me to get the content?

**Comment by alexgand** [comment]
Please try again, the code was modified and is now much better.
