### ISSUE TITLE
Add the ability to download specific categories (column English Package Name)

### ISSUE THREAD

**Issue by matiasg** [alexgand/springer_free_books#59]
It would be nice if you could run it like
```sh
python3 main.py --category "Mathematics and Statistics" --category "Physics and Astronomy"
```
and get only those categories downloaded.

**Comment by matiasg** [comment]
well, it seems that it is already done
in https://github.com/alexgand/springer_free_books/pull/57/

:+1:

**Comment by alexgand** [comment]
Yes, it is done in PR #57, already merged.
