### ISSUE TITLE
Unable to install requirements

### ISSUE THREAD

**Issue by jesusgt** [alexgand/springer_free_books#68]
Python version: 3.5.2
OS: Ubuntu 16.04.5 LTS

After activating the venv, and launching the command "pip install -r requirements.txt"

I get an error:
`Collecting certifi==2020.4.5.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-an>
Collecting chardet==3.0.4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting et-xmlfile==1.0.1 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Collecting idna==2.9 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Collecting jdcal==1.4.1 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Collecting numpy==1.18.2 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ff/18/c0b937e2f84095ae230196899e56d1d7d76c8e8424fb235ed7e5bb6d68af/numpy-1.18.2-cp35-cp35m-manylinux1>
Collecting openpyxl==3.0.3 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/95/8c/83563c60489954e5b80f9e2596b93a68e1ac4e4a730deb1aae632066d704/openpyxl-3.0.3.tar.gz
Collecting pandas==1.0.3 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/2f/79/f236ab1cfde94bac03d7b58f3f2ab0b1cc71d6a8bda3b25ce370a9fe4ab1/pandas-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gs8_q9nv/pandas/setup.py", line 42
        f"numpy >= {min_numpy_ver}",
                                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c8xdz0d6/pandas/
You are using pip version 8.1.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
No idea what I am doing wrong. Any help would be much appreciated. Thanks in advance

**Comment by ulisesfronze** [comment]
it's because f'' strings are only in python 3.6 and above, i recommend you to upgrade your python version :)

**Comment by jesusgt** [comment]
That certainly worked. Many thanks ulisesfronze.

**Comment by pedro-nonfree** [comment]
please, include that it does not work in debian stretch with python3 (you have to go for python2.7) because it uses python 3.5, not enough (3.6 required, maybe, not tested)
