### ISSUE TITLE
AttributeError: 'Int64Index' object has no attribute 'array'

### ISSUE THREAD

**Issue by pingsutw** [alexgand/springer_free_books#76]
After ran `python3 main.py -f ./books`, I got the following error.
```bash
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    books.index = [i + 2 for i in books.index.array]        # Recorrect indices
AttributeError: 'Int64Index' object has no attribute 'array'
```
python 3.7.5
ubuntu 19.10

**Comment by sapcat7** [comment]
I had the same issue, use the requirements file in order to download all modules required:
`pip3 install -r requirements.txt`
After that 
`python3 main.py`
worked for me

**Comment by white-glider** [comment]
Change line 70 in the `main.py` file to be:
`books.index = [i + 2 for i in books.index]`

**Comment by Aquilius94** [comment]
> Change line 70 in the `main.py` file to be:
> `books.index = [i + 2 for i in books.index]`

This has solved the issue for me.

**Comment by ebrillblaiddes** [comment]
Had same problem, white-glider's suggestion

> Change line 70 in the `main.py` file to be:
> `books.index = [i + 2 for i in books.index]`

worked for me and now I'm downloading a library.

**Comment by alexgand** [comment]
Corrected in the code, now it should work. Thanks!
