### ISSUE TITLE
Where are the downloaded files?

### ISSUE THREAD

**Issue by alexhkurz** [alexgand/springer_free_books#87]
Hi, thanks a lot for this program ... but I cannot find the downloaded files. I tried various versions of 

docker build . -t springer-image
docker run --rm -v [local_download_folder]:/app/downloads springer-image

**Comment by dbautistav** [comment]
If you followed the [instructions for docker](https://github.com/alexgand/springer_free_books#docker-container-to-do-all-the-work):

> cd \home\[user]\workspace
git clone https://github.com/alexgand/springer_free_books.git
cd springer_free_books
mkdir downloads
docker build . -t springer-image
docker run --rm -v [local_download_folder]:/app/downloads springer-image

You can replace `[local_download_folder]` with:
`\home\[user]\workspace\springer_free_books\downloads`.
Note that you still need to update your [user] path.

For example, in linux:
`docker run --rm -v ~/springer_free_books/downloads:/app/downloads springer-image`

[Read more about volumes.](https://docs.docker.com/storage/volumes)

**Comment by alexhkurz** [comment]
Thanks ... this works.
